"""empty message

Revision ID: f4519747ff88
Revises: 
Create Date: 2020-12-23 18:12:25.858820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4519747ff88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['Actors.id'], name='performance_actor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], name='performance_movie_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='performance_pkey')
    )
    # ### end Alembic commands ###
